# Generated by Django 5.0.7 on 2024-07-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molduck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='output_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
