# Generated by Django 5.0.7 on 2024-07-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molduck', '0002_alter_job_output_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
    ]
