# Generated by Django 5.0.7 on 2024-07-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molduck', '0004_job_executed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='executed',
        ),
        migrations.RemoveField(
            model_name='job',
            name='success',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'awaiting'), (2, 'running'), (3, 'failed'), (4, 'succeded')], default=1),
        ),
    ]
